### ISSUE TITLE
refactor to gRPC-based generic command spawner

### ISSUE THREAD

**Issue by markfisher** [projectriff/command-function-invoker#1]
this could be implemented in Go

need to consider handling of streams as well as item-at-a-time

**Comment by glyn** [comment]
Implemented by https://github.com/projectriff/shell-function-invoker/commit/67b83cef345083dc1b5d9ca6561aed3dff53f659.

**Comment by glyn** [comment]
Really need to merge https://github.com/projectriff/riff/pull/278 before closing this issue. @ericbottard - please could you re-review when you have some time?
