### ISSUE TITLE
The matchers pattern for command is too "greedy"

### ISSUE THREAD

**Issue by trisberg** [projectriff/command-function-invoker#10]
If I install the command invoker resource I get an error for all other types of functions unless I specify --artifact. A simple `riff init` returns `Artifact must be specified` in square directory with a `square.js` file plus some other file, like a `README.md` or `.dockerignore`.

**Comment by trisberg** [comment]
Also see `Multiple matching invokers found, pick one of: command, node:` depending on what files are in the directory

**Comment by scothis** [comment]
The general issue is that commands have no file pattern or extension. We could remove the matchers entirely and force the invoker and artifact to be specified for the commands. It's a better tradeoff then forcing every other invoker to need to specify an artifact when the command invoker is installed.

```
riff init command -a foobar
```

**Comment by trisberg** [comment]
We could have some common extensions like  "*.sh"

**Comment by scothis** [comment]
If it were still the shell-invoker I'd agree, but as the command-invoker using `*.sh` feels wrong.

**Comment by ericbottard** [comment]
Or should we try to auto-order them like so:
1. pure wildcard
2. wildcard and something else (typically extension)
3. no wildcard?

**Comment by scothis** [comment]
You're welcome to [take a crack at it](https://github.com/projectriff/riff/blob/c24bfeb7016633bd3384ffaaa5eb120f0a3d15cd/riff-cli/pkg/initializer/initializer.go#L85). I punted since no matter how much effort we put in to detecting the artifact/invoker, it still won't be consistent between calls if the invokers in the cluster change, unless the invoker and artifact are specified by the user.

**Comment by jldec** [comment]
How about requiring **just** the invoker to be specified for 'riff init <invoker>' or 'riff create <invoker>'? Requiring both invoker **and** artifact seems like overkill.

**Comment by ericbottard** [comment]
This issue is stale now, detection will happen in the riff buildpack
